language: php

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
- composer install --dev

script:
  - vendor/bin/phpunit -c phpunit.xml
  - vendor/bin/phpdoc --template="checkstyle" -d src/ && if [[ `cat "output/checkstyle.xml" | grep "<error "` != "" ]]; then exit 1; fi